steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-f"
      - Dockerfile.dataflow
      - "-t"
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
      - .
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
    id: Push
    
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - insightbee-crawler          # ← Cloud Run Job 이름
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID
      - --region=europe-west1
      - --project=sesac-yoojikol
    id: UpdateJob

images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_REPO_NAME/$_SERVICE_NAME:$BUILD_ID

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REPO_NAME: insightbee
  _SERVICE_NAME: insightbee-dataflow
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: sesac-yoojikol
  _AR_REPOSITORY: cloud-run-source-deploy
