FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .


ARG VITE_API_BASE_URL=https://insightbee-950949202751.europe-west1.run.app

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV PORT=8080

RUN npm run build

CMD ["sh", "-c", "npm run preview -- --host 0.0.0.0 --port ${PORT}"]
